[[wget]]
arch = "aarch64"
git-tree-sha1 = "490e9a488a4587b762e6efc95ad8ef1c3f9b1149"
os = "macos"

    [[wget.download]]
    sha256 = "74cdb5362cacadfa52dd673747438ecf03174d1b489dc5eabc1e9c2524f4d4db"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.aarch64-apple-darwin.tar.gz"
[[wget]]
arch = "aarch64"
git-tree-sha1 = "1b95188f63393c973aec820b55ef967d031fd3e2"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "3aa76b70761d12987113d6120c933ef96f5890169982682446cdde7792282f5b"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.aarch64-linux-gnu.tar.gz"
[[wget]]
arch = "aarch64"
git-tree-sha1 = "bf96a215c1f63a5909ffd7e670e54781d9e89f9c"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "0b86d5009f0c67b3354787362e0fbdfb90e2f9e9c41df0fad6a8a7c99f2aecdb"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.aarch64-linux-musl.tar.gz"
[[wget]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e145a376670081da3629fe99b951c708bd89b50c"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "8dc459e9614366592fbc753a660ae0b876192aefea09b428e6c7e4e3a0d41214"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.armv6l-linux-gnueabihf.tar.gz"
[[wget]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f646d5ae60f2cbbcf16b9bca7a6a3c72ddfc0bd"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "36d0fa7becf489552f1b70a15ded2450efb7e169510112df5e29e234b216cb08"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.armv6l-linux-musleabihf.tar.gz"
[[wget]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62b9c9c5864843b447413a80716a9e13c5f99650"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "d666540a3523cb4cbf096d7904081fdb5e8f3645a95f06671cad335392864318"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.armv7l-linux-gnueabihf.tar.gz"
[[wget]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d951f28fcd1f3487d0a3c7d2dc4d9ac59244d203"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "de2339e8e4e0ce64fc79a508645a13082f8f03af0339739f95671c10825c7a01"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.armv7l-linux-musleabihf.tar.gz"
[[wget]]
arch = "i686"
git-tree-sha1 = "898d90a8917118ebd24e4b94821c0aa8338b7a21"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "4de8a38afcb233c49eb6553b611b5e40e95df5f302616c2589782feddfd6f92c"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.i686-linux-gnu.tar.gz"
[[wget]]
arch = "i686"
git-tree-sha1 = "ffa660b7571cd17130bcc3904f0ce422f49246c0"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "2b633ed34ab15288b36cb7b3823b5fd27f1398ecc9f3d7db2cf15dc94bd33b4c"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.i686-linux-musl.tar.gz"
[[wget]]
arch = "powerpc64le"
git-tree-sha1 = "74412687409b45338a6e162d7b5c91ff83049460"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "0f53f7a7003b2883cf0083874a860dadc1c8f717d3c25a0cab1946f457ffc697"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.powerpc64le-linux-gnu.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "7fb6ec69026ca755bdf616f6216e17de466ad1c4"
os = "macos"

    [[wget.download]]
    sha256 = "38a6ba4758dd084623a1c2052606830107846518cfa296e053c88f85ddf500d4"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.x86_64-apple-darwin.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "dadd0263ee695b15d5aad12efec8d1250b75ab0b"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "9885628cddb758f9e596bb0c479071b8f251b86034160aaf4c02e8350ca414d5"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.x86_64-linux-gnu.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "64bd466b6c8e6d718b1364fb115eaea884b9ed7f"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "89ff4eca4de332349362a80993e9bde797d179b44a35314cee46b8cf78aeed43"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.x86_64-linux-musl.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "759dc4f741e5409285f131cdb9dee8eaa0d67d3e"
os = "freebsd"

    [[wget.download]]
    sha256 = "e43e8432644abe0c66d108cdea1ba6c2e5ba481b3da68e3133f2ac314b1d3fec"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.4+0/wget.v1.21.4.x86_64-unknown-freebsd.tar.gz"
