[[wget]]
arch = "aarch64"
git-tree-sha1 = "683bfd62e04c3b37d5dac437a0c17cf3315b2841"
os = "macos"

    [[wget.download]]
    sha256 = "d44eef0df9171200e1b52ac3741c6c71127b4cb519ad9eb43012f043698c824d"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.aarch64-apple-darwin.tar.gz"
[[wget]]
arch = "aarch64"
git-tree-sha1 = "6846549f4509c0d6afdc827b92fd39fb64528271"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "4af32e71c944b4db3161b7f0962352a085aa67b1c07971552b9a267a5e618d26"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.aarch64-linux-gnu.tar.gz"
[[wget]]
arch = "aarch64"
git-tree-sha1 = "af82134c7af38a0bc05c43a216b994b58e1b990f"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "b4097c91e3ddd55bbf2589eebe0ed03f1bea5816cabe120838c3e3cf03fe809d"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.aarch64-linux-musl.tar.gz"
[[wget]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5eafb556e9728518f85e02d9cdc530181085acf5"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "8826cd374c53d540ed38d917ac9c89d635a72a184fc0b6a572beed2a482648a8"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.armv6l-linux-gnueabihf.tar.gz"
[[wget]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "62aeb7a131d4221c1de347ba331fd9a28ba2e866"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "ffb0536116f729aa88f8e4aa2868106fda028c3f3e150af97c295a9aa849db8a"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.armv6l-linux-musleabihf.tar.gz"
[[wget]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4acd02f152bcf471bc01db7d0de2120df9eaa35"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "3781075847151d86ad923a29d43605127e0ba4dcef2c0720697b4432fad7dffe"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.armv7l-linux-gnueabihf.tar.gz"
[[wget]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68d77b73a07c6c3e87d2500d09b56baf756a32d2"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "591a7ad4d80e828729550a958810d15935e97fdd1aaf36f5e583677e8d55981d"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.armv7l-linux-musleabihf.tar.gz"
[[wget]]
arch = "i686"
git-tree-sha1 = "4c677ffbb32d01a9795fe776dc3e6ae2af52ac27"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "82ba7e04ec4541d62c8c160a0fd7a711c27b236dd2b8a83a14d961d16661040f"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.i686-linux-gnu.tar.gz"
[[wget]]
arch = "i686"
git-tree-sha1 = "848d4bdac3bf8754355a31dd2ddf042855ed2d2f"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "0618bb02b1c4e5977b6b0e18642cef6a7102ab09403c076f2bfdf9c7b3761dda"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.i686-linux-musl.tar.gz"
[[wget]]
arch = "powerpc64le"
git-tree-sha1 = "2a96e0a6f713bc18d13f5d53b750c6f6aaefe25b"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "4f604f55129cb4ebe99ee0e696cd67e5a2e2fc1ddcb4429806d688a506019a0e"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.powerpc64le-linux-gnu.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "c4efc7aac479c7ceb4c247fd7e400dc9f6a26c18"
os = "macos"

    [[wget.download]]
    sha256 = "b37e0ce9015711e64aa0e4d188f1e66028fc04c4ede3817b3cd04679b90ee617"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.x86_64-apple-darwin.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "ba0ce90ff3e9a5ec475369ce4c0239c81f13d39c"
libc = "glibc"
os = "linux"

    [[wget.download]]
    sha256 = "6fabe4ad83d559ace5321c5a18552189b55fc63a59e19bde5aa3a804f089f06f"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.x86_64-linux-gnu.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "7fd3a66433ada15c3f1819cf09cc3369edd91bf9"
libc = "musl"
os = "linux"

    [[wget.download]]
    sha256 = "6ae637e2dfdb86d2aaf1bc562baa990803b69491b2c8b28bc9df0f26b105b24a"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.x86_64-linux-musl.tar.gz"
[[wget]]
arch = "x86_64"
git-tree-sha1 = "89036225bbcff20a665b0ee8bf08eab2b47232e9"
os = "freebsd"

    [[wget.download]]
    sha256 = "5a02a90a9353a47e7d3989d71e57cf314ca363c347902ff9820db72e57ceea2f"
    url = "https://github.com/JuliaBinaryWrappers/wget_jll.jl/releases/download/wget-v1.21.1+0/wget.v1.21.1.x86_64-unknown-freebsd.tar.gz"
